<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Data Pemohon — IPPT Kota Yogyakarta</title><script>(()=>{const s=localStorage.getItem('theme');document.documentElement.classList.toggle('dark',s==='dark'||((!s||s==='system')&&matchMedia('(prefers-color-scheme: dark)').matches));})();</script>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-50 text-slate-900 antialiased transition-colors duration-200 dark:bg-slate-950 dark:text-slate-100">
<header class="border-b border-slate-200 bg-white/95 dark:border-slate-800 dark:bg-slate-950/95"><div class="mx-auto flex min-h-16 max-w-6xl items-center justify-between gap-4 px-5 sm:px-8"><a href="{{ route('landing') }}" class="flex items-center gap-3"><img src="{{ asset('images/logo.png') }}" alt="Logo Pemerintah Kota Yogyakarta" class="h-10 w-auto" onerror="this.onerror=null;this.src='{{ asset('image/logo.png') }}';"><span class="border-l border-slate-200 pl-3 text-sm font-bold dark:border-slate-700">Layanan IPPT</span></a><div class="flex items-center gap-2"><button type="button" data-theme-cycle class="grid size-10 place-items-center rounded-xl border border-slate-200 text-slate-600 hover:bg-slate-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-900" aria-label="Ganti tema" title="Ganti tema"><span data-theme-toggle-icon class="block size-5" aria-hidden="true"></span></button><a href="{{ route('filament.admin.dashboard') }}" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white hover:bg-slate-800 dark:bg-white dark:text-slate-950">Panel Pemohon</a></div></div></header>
<main class="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:py-14"><div class="mx-auto max-w-3xl"><div class="mb-8"><p class="text-xs font-extrabold uppercase tracking-[.16em] text-amber-600 dark:text-amber-400">Tahap 1 dari 2</p><h1 class="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Lengkapi data pemohon</h1><p class="mt-3 max-w-2xl text-sm leading-7 text-slate-600 dark:text-slate-300">Data ini menjadi identitas Anda di layanan IPPT. Setelah dikirim, petugas memeriksa data sebelum pengajuan permohonan dibuka.</p></div>
@if(session('success'))<div class="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800 dark:border-emerald-900/60 dark:bg-emerald-950/30 dark:text-emerald-300">{{ session('success') }}</div>@endif
@if(session('info'))<div class="mb-6 rounded-2xl border border-slate-200 bg-white p-4 text-sm text-slate-700 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-300">{{ session('info') }}</div>@endif
@php($status=$pemohon?->status_verifikasi??'belum_lengkap')
<div class="mb-7 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><div class="flex gap-4"><div class="grid size-10 shrink-0 place-items-center rounded-full bg-amber-100 text-amber-700 dark:bg-amber-400/10 dark:text-amber-300">1</div><div><p class="font-bold">Status data pemohon</p><p class="mt-1 text-sm text-slate-600 dark:text-slate-400">@switch($status)@case('terverifikasi') Data sudah diverifikasi. Anda dapat melanjutkan ke pengajuan permohonan.@break @case('menunggu_verifikasi') Data sudah dikirim dan sedang diperiksa petugas.@break @case('perlu_perbaikan') Data perlu diperbaiki sesuai catatan petugas.@break @default Lengkapi data di bawah, lalu kirim untuk diperiksa petugas.@endswitch</p>@if($pemohon?->catatan_verifikasi)<div class="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-200"><strong>Catatan petugas:</strong> {{ $pemohon->catatan_verifikasi }}</div>@endif</div></div></div>
@if($status !== 'terverifikasi')<form method="POST" action="{{ route('pemohon.profil.update') }}" class="space-y-6">@csrf
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-8"><div class="border-b border-slate-100 pb-5 dark:border-slate-800"><h2 class="font-extrabold">Identitas pemohon</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Pilih jenis pemohon terlebih dahulu.</p></div><div class="mt-6 grid gap-5 sm:grid-cols-2">
<label class="sm:col-span-2"><span class="mb-2 block text-sm font-bold">Jenis pemohon <span class="text-red-500">*</span></span><select name="jenis_pemohon" id="jenis_pemohon" required class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"><option value="perorangan" @selected(old('jenis_pemohon',$pemohon?->jenis_pemohon)==='perorangan')>Perorangan</option><option value="badan" @selected(old('jenis_pemohon',$pemohon?->jenis_pemohon)==='badan')>Badan / badan hukum</option></select></label>
<label class="sm:col-span-2"><span class="mb-2 block text-sm font-bold">Nama pemohon / badan <span class="text-red-500">*</span></span><input name="nama" value="{{ old('nama',$pemohon?->nama??$user->name) }}" required class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"><x-error field="nama" /></label>
<label id="nik-wrap"><span class="mb-2 block text-sm font-bold">NIK <span class="text-red-500">*</span></span><input name="nik" inputmode="numeric" maxlength="16" value="{{ old('nik',$pemohon?->nik) }}" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"><x-error field="nik" /></label>
<label id="nib-wrap"><span class="mb-2 block text-sm font-bold">NIB <span class="text-red-500">*</span></span><input name="nib" inputmode="numeric" maxlength="13" value="{{ old('nib',$pemohon?->nib) }}" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"><x-error field="nib" /></label>
<label><span class="mb-2 block text-sm font-bold">NPWP</span><input name="npwp" inputmode="numeric" maxlength="16" value="{{ old('npwp',$pemohon?->npwp) }}" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"></label><label><span class="mb-2 block text-sm font-bold">Nomor telepon / WhatsApp <span class="text-red-500">*</span></span><input name="nomor_telepon" value="{{ old('nomor_telepon',$pemohon?->nomor_telepon) }}" required class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"><x-error field="nomor_telepon" /></label><div class="sm:col-span-2 rounded-xl bg-slate-50 p-4 text-sm text-slate-600 dark:bg-slate-950 dark:text-slate-400">Email akun: <strong class="text-slate-900 dark:text-white">{{ $user->email }}</strong></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:p-8"><div class="border-b border-slate-100 pb-5 dark:border-slate-800"><h2 class="font-extrabold">Alamat pemohon</h2><p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Isi alamat yang dapat digunakan untuk komunikasi administrasi.</p></div><div class="mt-6 grid gap-5 sm:grid-cols-2"><label class="sm:col-span-2"><span class="mb-2 block text-sm font-bold">Alamat lengkap <span class="text-red-500">*</span></span><textarea name="alamat" rows="3" required class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950">{{ old('alamat',$pemohon?->alamat) }}</textarea><x-error field="alamat" /></label><label><span class="mb-2 block text-sm font-bold">Kelurahan / Kalurahan</span><input name="kelurahan" value="{{ old('kelurahan',$pemohon?->kelurahan) }}" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"></label><label><span class="mb-2 block text-sm font-bold">Kecamatan / Kapanewon</span><input name="kecamatan" value="{{ old('kecamatan',$pemohon?->kecamatan) }}" class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-950"></label><label><span class="mb-2 block text-sm font-bold">Kota / Kabupaten <span class="text-red-500">*</span></span><input name="kota" value="{{ old('kota',$pemohon?->kota??'Yogyakarta') }}" required class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm dark:border-slate-700 dark:bg-slate-950"><x-error field="kota" /></label></div></section>
<div class="flex flex-col-reverse gap-3 sm:flex-row sm:justify-between"><a href="{{ route('landing') }}" class="rounded-xl border border-slate-300 px-5 py-3 text-center text-sm font-bold dark:border-slate-700">Kembali</a><button class="rounded-xl bg-amber-500 px-6 py-3 text-sm font-extrabold text-slate-950 hover:bg-amber-400">Kirim untuk Verifikasi</button></div></form>
@else<div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-6 dark:border-emerald-900/50 dark:bg-emerald-950/20"><p class="font-extrabold text-emerald-800 dark:text-emerald-300">Data pemohon telah terverifikasi.</p><p class="mt-2 text-sm text-emerald-700 dark:text-emerald-400">Anda sekarang dapat membuat permohonan IPPT dari panel pemohon.</p><a href="{{ route('filament.admin.dashboard') }}" class="mt-5 inline-flex rounded-xl bg-emerald-700 px-5 py-3 text-sm font-bold text-white">Masuk ke Panel Pemohon</a></div>@endif
</div></main><script>const t=document.getElementById('jenis_pemohon'),n=document.getElementById('nik-wrap'),b=document.getElementById('nib-wrap');function s(){const x=t?.value==='badan';n?.classList.toggle('hidden',x);b?.classList.toggle('hidden',!x)}t?.addEventListener('change',s);s();</script></body></html>
